proyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('select2.urls')),
    url(r'^$', RedirectView.as_view(url='/admin', permanent=True), name='home'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^admin/', include('articulo.urls')),
    url(r'^admin/', include('cheque.urls')),
    url(r'^admin/', include('cliente.urls')),
    url(r'^admin/', include('configuracion.urls')),
    url(r'^admin/', include('venta.urls')),
    url(r'^admin/', include('movimientos.urls')),
    #url(r'^admin/', include('ivaAfip.urls')),
]

venta/urls.py
from django.conf.urls import include, url
from venta import views
from cliente.views import cliente_json

urlpatterns = [url(r"^generarRemito/(\d+)$", views.generar_remito, name='generarRemito'),
               url(r"^generarFactura/(\d+)$", views.generar_factura, name='generarFactura'),
               url(r"^generarPresupuesto/(\d+)$", views.generar_presupuesto, name='generarPresupuesto'),
               url(r"^generarNotaCredito/(\d+)$", views.generarNotaCredito, name='generarNotaCredito'),
              # url(r"^crearVenta/(\d+)$", views.crearVenta, name='crearVenta'),
               url(r"^generarCompra/(\d+)$", views.generar_compra, name='generarCompra'),
               url(r"^pagina_error/(?P<codigo>.+)$", views.pagina_error, name='pagina_error'),
               url(r"^notaCredito/$", views.notaCredito, name='notaCredito'),
               url(r"^ivaventas/$", views.ivaventas, name='ivaventas'),
               url(r"^exportar_facturas/$", views.exportar_facturas, name='exportar_facturas'),
               url(r"^getFacturas/(\d+)$", views.getFacturas, name='getFacturas'),
               url(r'^remito_json/(?P<oid>[0-9]+)/$', views.remito_json, name='remito_json'),
               url(r'^ventas_json/(?P<Iday>\d{1,2})/(?P<Imonth>\d{1,2})/(?P<Iyear>\d{4})/(?P<Fday>\d{1,2})/(?P<Fmonth>\d{1,2})/(?P<Fyear>\d{4})/$', views.ventas_json, name='ventas_json'),
               url(r'^tarjeta_json/(?P<oid>[0-9]+)/$', views.tarjeta_json, name='tarjeta_json'),
               url(r"^caja_diaria_json/(?P<parametro>.+)$", views.caja_diaria_json, name='caja_diaria_json'),
               url(r"^recargo_tarjeta/(?P<nombre>.+)/(?P<cuotas>\d{1,2})/$", views.recargo_tarjeta, name='recargo_tarjeta'),
               url(r"^generar_archivos_contador/$", views.contador_ventas, name='contador_ventas'),
               url(r"^descargar_archivo_contador_ventas", views.descargar_archivo_contador_ventas, name="descargar_archivo_contador_ventas"),
               #url(r'^cliente_json/(?P<oid>[0-9]+)/$', cliente_json, name='cliente_json'),
]

venta/models.py
# -*- coding: utf-8 -*-
import datetime
from django.db import models
import select2.fields
import select2.models
from django.db.models import Q
from django.dispatch import receiver
from itertools import chain
from cliente.models import Cliente, ClienteResumen, Vendedor
from articulo.models import Articulo
from django.contrib.contenttypes.models import ContentType
from django.db.models.signals import post_save, pre_save, post_delete, pre_delete
from smart_selects.db_fields import ChainedForeignKey

from cliente.views import actualizar_cuenta_corriente, crear_cliente_resumen
from configuracion.views import TIPO_FACTURA, TIPO_PAGO, TIPO_VENTA, Tipo, TipoPago


class Tarjeta(models.Model):
    nombre = models.CharField(u'Nombre', max_length=100)
    #recargo = models.DecimalField(u'% Recargo', max_digits=10, decimal_places=2, default=0)

    def __unicode__(self):
        return self.nombre


class Cuota(models.Model):
    tarjeta = models.ForeignKey(Tarjeta, related_name='cuota_tarjeta', on_delete=models.CASCADE)
    cuota = models.IntegerField(u'Cuota', default=0)
    recargo = models.DecimalField(u'% Recargo', max_digits=10, decimal_places=2, default=0.00)

    def __unicode__(self):
        return u'{0}'.format(self.cuota)


class Venta(models.Model):
    numero = models.CharField(u'numero venta', max_length=60, default='')
    punto_venta = models.CharField(u'Punto Venta', max_length=5, default='')
    tipo_venta = models.CharField(u'Tipo', max_length=150, choices=TIPO_VENTA, default=Tipo.PRESUPUESTO)
    fecha = models.DateField(u'Fecha', default=datetime.date.today)
    tipo_factura = models.CharField(u'Tipo de Factura', max_length=100, choices=TIPO_FACTURA, default='X')
    cliente = select2.fields.ForeignKey(Cliente,
                                        ajax=False,
                                        search_field=lambda q: Q(nombre__icontains=q) | Q(apellido__icontains=q) | Q(
                                            dni_cuit__icontains=q),
                                        related_name=u'Cliente',
                                        overlay="...",
                                        js_options={
                                            'quiet_millis': 200,
                                        },
                                        on_delete=models.PROTECT)
    neto_gravado = models.DecimalField(u'NETO GRAVADO', max_digits=20, decimal_places=2, default=0.00)
    iva = models.DecimalField(u'IVA', max_digits=20, decimal_places=2, default=0.00)
    total = models.DecimalField(u'TOTAL', max_digits=20, decimal_places=2, default=0.00)
    forma_pago = models.CharField(u'Forma de Pago', max_length=100, choices=TIPO_PAGO, default='Cuenta Corriente')
    cae = models.CharField(u'CAE', max_length=100, default='No es Factura Digital')
    vencimiento_cae = models.DateField(u'Vencimiento CAE', blank=True, null=True)
    venta_nota = models.ForeignKey('Venta', related_name='asociada', on_delete=models.PROTECT, blank=True, null=True)
    tarjeta = select2.fields.ForeignKey(Tarjeta,
                                        ajax=True,
                                        blank=True, null=True,
                                        search_field=lambda q: Q(nombre__icontains=q),
                                        related_name=u'tarjeta',
                                        overlay="...",
                                        js_options={
                                            'quiet_millis': 200,
                                        },
                                        on_delete=models.PROTECT)
    descuento = models.DecimalField(u'Descuento', max_digits=8, decimal_places=2, default=0.00)
    recargo = models.DecimalField(u'Recargo', max_digits=8, decimal_places=2, default=0.00)
    vendedor = models.ForeignKey(Vendedor, related_name='vendedor_venta', blank=True, null=True)
    cuota = ChainedForeignKey('Cuota',
                                chained_field="tarjeta",
                                chained_model_field="tarjeta",
                                show_all=False,
                                auto_choose=False,
                                blank =True,
                                null =True,
                                )
    percepcion_iibb = models.DecimalField(u'Percepcion ingresos brutos', max_digits=20, decimal_places=2, default=0.00)
    monto_iva21 = models.DecimalField(u'IVA 21', max_digits=20, decimal_places=2, default=0.00)
    monto_iva10 = models.DecimalField(u'IVA 10', max_digits=20, decimal_places=2, default=0.00)
    monto_iva27 = models.DecimalField(u'IVA 27', max_digits=20, decimal_places=2, default=0.00)

    class Meta:
        verbose_name = u'Venta'
        verbose_name_plural = u'Ventas'

    def __unicode__(self):
        if not self.numero == '':
            if self.tipo_venta == Tipo.COMPRA:
                return "{:08d}".format(int(self.numero))
            else:
                return "{:04d}".format(int(self.punto_venta)) + "{:08d}".format(int(self.numero))
        return ''


# --Articulo
class VentaArticulo(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    articulo = select2.fields.ForeignKey(Articulo,
                                         ajax=True,
                                         search_field=lambda q: Q(codigo__icontains=q),
                                         related_name=u'ArticulosVenta',
                                         overlay="...",
                                         js_options={
                                             'quiet_millis': 200,
                                         },
                                         on_delete=models.PROTECT)
    descripcion = models.CharField(u'descripción', max_length=150, default='')
    cantidad = models.DecimalField(u'Cantidad', max_digits=12, decimal_places=2, default=0.00)
    precio = models.DecimalField(u'Precio Unitario', max_digits=20, decimal_places=2, default=0.00)
    iva = models.DecimalField(u'IVA (%)', max_digits=4, decimal_places=2, default=0.00)
    total = models.DecimalField(u'Total', max_digits=20, decimal_places=2, default=0.00)

    class Meta:
        verbose_name = u'Articulo'
        verbose_name_plural = u'Articulo'


@receiver(post_delete, sender=VentaArticulo)
def venta_articulo_post_delete(sender, instance, **kwargs):
    if not instance.venta.tipo_venta == Tipo.COMPRA and not instance.venta.tipo_venta == Tipo.PRESUPUESTO:
        if instance.venta.tipo_venta == Tipo.REMITO:
            art = Articulo.objects.get(id=instance.articulo.id)
            art.stock += instance.cantidad
            art.save()
        elif instance.venta.tipo_venta == Tipo.FACTURA:
            art = Articulo.objects.get(id=instance.articulo.id)
            art.stock += instance.cantidad
            art.save()
        elif instance.venta.tipo_venta == Tipo.NOTA and instance.venta.facturado:
            art = Articulo.objects.get(id=instance.articulo.id)
            art.stock -= instance.cantidad
            art.save()
        # caso compra si llega a ser necesario
        # elif instance.venta.tipo_venta == Tipo.COMPRA:
        #    art = Articulo.objects.get(id=instance.articulo.id)
        #    art.stock -= instance.cantidad


@receiver(pre_save, sender=VentaArticulo)
def venta_articulo_pre_save(sender, instance, raw, using, update_fields, **kwargs):
    if VentaArticulo.objects.filter(id=instance.id).exists():
        old_art = VentaArticulo.objects.get(id=instance.id)
        diferencia = old_art.cantidad - instance.cantidad
        if instance.venta.tipo_venta == Tipo.REMITO and not diferencia == 0:
            art = Articulo.objects.get(id=instance.articulo.id)
            art.stock += diferencia
            art.save()
        # caso compra si llega a ser necesario
        # if instance.venta.tipo_venta == Tipo.COMPRA and not diferencia == 0:
        #    art = Articulo.objects.get(id=instance.articulo.id)
        #    art.stock += diferencia
        #    art.save()


# en caso de ser un remito o factura X actualizo el total en el resumen
@receiver(pre_save, sender=Venta)
def venta_pre_save(sender, instance, raw, using, update_fields, **kwargs):
    content_type = ContentType.objects.get(app_label=instance._meta.app_label, model=instance._meta.model_name)
    if instance.tipo_venta == Tipo.REMITO or (instance.tipo_venta == Tipo.FACTURA and instance.tipo_factura == 'X'):
        if ClienteResumen.objects.filter(content_type=content_type, object_id=instance.pk).exists():
            cliente_resumen = ClienteResumen.objects.get(content_type=content_type, object_id=instance.pk)
            cliente_resumen.debe = instance.total
            cliente_resumen.fecha = instance.fecha
            cliente_resumen.save()
            actualizar_cuenta_corriente(instance.cliente)


@receiver(post_delete, sender=Venta)
def venta_post_delete(sender, instance, **kwargs):
    content_type = ContentType.objects.get(app_label=instance._meta.app_label, model=instance._meta.model_name)
    if ClienteResumen.objects.filter(content_type=content_type, object_id=instance.pk).exists():
        cliente_resumen = ClienteResumen.objects.get(content_type=content_type, object_id=instance.pk)
        cliente = cliente_resumen.cliente
        cliente_resumen.delete()
        actualizar_cuenta_corriente(cliente)


class TokenAfip(models.Model):
    token = models.TextField(u'Token')
    sign = models.TextField(u'Sign')
    fecha = models.DateTimeField(u'Fecha')


class CompraManager(models.Manager):
    def get_queryset(self):
        return super(CompraManager, self).get_queryset(). \
            filter(tipo_venta=Tipo.COMPRA)


class Compra(Venta):
    objects = CompraManager()

    def save(self, *args, **kwargs):
        self.tipo_venta = Tipo.COMPRA
        super(Compra, self).save(*args, **kwargs)

    class Meta:
        proxy = True
        ordering = ('-fecha',)
        verbose_name = "Compra"

venta/forms/forms.py
# -*- coding: utf-8 -*-
# vim:expandtab ts=4 sw=4
from django import forms
from functools import partial

DateInput = partial(forms.DateInput, {'class': 'datepicker form-control vDateField  ', 'id': "fechaI"})
DateInput2 = partial(forms.DateInput, {'class': 'datepicker form-control vDateField ', 'id': "fechaF"})


class formNotaCredito(forms.Form):
    Cliente = forms.IntegerField(widget=forms.Select(attrs={'class': "form-control"}))
    Venta = forms.IntegerField(widget=forms.Select(attrs={'class': "form-control"}))


class formVentas(forms.Form):
    fecha_inicio = forms.DateField(label=u'Fecha Desde', widget=DateInput2())
    fecha_fin = forms.DateField(label=u'Fecha Hasta', widget=DateInput())
    neto_gravado = forms.DecimalField(widget=forms.TextInput(attrs={'class': "form-control vTextField"}))
    iva = forms.DecimalField(max_digits=20, decimal_places=2, widget=forms.NumberInput(attrs={'class': "form-control vTextField"}))
    total = forms.DecimalField(max_digits=20, decimal_places=2, widget=forms.NumberInput(attrs={'class': "form-control vTextField"}))

venta/views/caja_diaria.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse

from cliente.models import ClienteResumen, Q
from configuracion.views import Tipo, TipoPago
from venta.models import Venta


def parametrizar(parametro):
    parametro = parametro.split('/')
    parametros = parametro[0].split("&")
    d = dict()
    for p in parametros:
        par = p.split('=')
        d.update({par[0]: par[1]})
    return d

@login_required
def caja_diaria_json(request, parametro):
    d = parametrizar(parametro)
    ventas = ClienteResumen.objects.filter(**d)
    ingreso_tarjeta = 0
    ingreso_efectivo = 0
    egreso_tarjeta = 0
    egreso_efectivo = 0

    facturas = ventas.filter(tipo=Tipo.FACTURA)
    for f in facturas:
        venta = Venta.objects.get(id=f.object_id)
        if venta.forma_pago == TipoPago.TARJETA:
            ingreso_tarjeta += float(venta.total)
        elif venta.forma_pago == TipoPago.EFECTIVO:
            ingreso_efectivo += float(venta.total)

    compras = ventas.filter(tipo=Tipo.COMPRA)
    for c in compras:
        venta = Venta.objects.get(id=c.object_id)
        if venta.forma_pago == TipoPago.TARJETA:
            egreso_tarjeta += float(venta.total)
        elif venta.forma_pago == TipoPago.EFECTIVO:
            egreso_efectivo += float(venta.total)

    ingreso = ventas.filter(tipo=Tipo.INGRESO ).aggregate(Sum('haber'))
    ingreso = float(ingreso['haber__sum'] or 0.0)
    ingreso_efectivo += ingreso

    pago = ventas.filter(Q(tipo=Tipo.PAGO)|Q(tipo=Tipo.EGRESO)).aggregate(Sum('debe'))
    pago = float(pago['debe__sum'] or 0.0)
    egreso_efectivo += pago

    recibo = ventas.filter(tipo=Tipo.RECIBO).aggregate(Sum('debe'))
    recibo = float(recibo['debe__sum'] or 0.0)
    ingreso_efectivo += recibo
    data = {
        'ingreso_tarjeta': ingreso_tarjeta,
        'ingreso_efectivo': ingreso_efectivo,
        'egreso_tarjeta': egreso_tarjeta,
        'egreso_efectivo': egreso_efectivo
    }
    return JsonResponse(data)

venta/views/compra.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import *
from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from articulo.views import stock_articulos
from cliente.models import ClienteResumen
from cliente.views import crear_cliente_resumen
from configuracion.models import Configuracion
from configuracion.views import Tipo
from venta.models import Compra, VentaArticulo

@login_required
def generar_compra(request, id):
        #template_name = "factura-remitoPDF.html"
        compra = Compra.objects.get(pk=id)
        articulos = VentaArticulo.objects.filter(venta=id)
        conf = Configuracion.objects.all()[0]
        content_type = ContentType.objects.get(app_label=compra._meta.app_label, model= compra._meta.model_name)
        if not ClienteResumen.objects.filter(content_type=content_type, object_id=compra.pk).exists():
            crear_cliente_resumen(compra, Tipo.COMPRA, compra.total, 0)
            stock_articulos(articulos, True)
        return HttpResponseRedirect("../cliente/clientemovimiento/")

venta/views/tarjeta.py
# -*- coding: utf-8 -*-
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse

from cliente.models import ClienteResumen, Q
from configuracion.views import Tipo, TipoPago
from venta.models import Tarjeta, Cuota

from django.http import JsonResponse

@login_required
def recargo_tarjeta(request, nombre, cuotas):
    recargo = Cuota.objects.select_related('tarjeta').get(tarjeta__nombre=nombre, cuota=cuotas).recargo
    data = {
        'recargo': recargo
    }
    return JsonResponse(data)

venta/templates/NotaCredito.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_admin/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />

 {% block title %}Nota de Credito | Administración{% endblock %}
{% block content %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
<form class="centrado" id="changelist-form" enctype="multipart/form-data" method="post" action={% url 'notaCredito' %}>
   {% csrf_token %}
  <fielset class="module aligned ">
    <div class=" col-lg-6  " >
      {% for field in form %}
            {{ field.errors }}

                  <div class="  col-lg-12 col-md-12 col-sm-12 pull-left" >
                      <div class="col-lg-6 margen-top tlabel">{{ field.label_tag }}</div>
                      {{ field }}
                  </div>
      {%endfor%}
      <button type="submit" class=" list-group-item active iva b ">
      <span class="text">Crear Nota de Credito</span></button>
    </div>
  </fielset>
</form>
{% endblock %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
{% block bootstrap_admin_js %}
  <script src="{% static 'bootstrap_admin/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap_admin/js/base.js' %}"></script>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
{% endblock bootstrap_admin_js %}
{% block js %}
<script>

  $.ajax({
      url: '/admin/all_clientes/',
      data: '',
  }).done(function( data ) {
    var options;
    options += '<option selected disabled > Seleccione un Cliente </option>';
    for (var i = 0; i < data.clientes.length; i++) {
      options += '<option value="' + data.clientes[i][0] + '">' + data.clientes[i][1] + ', ' + data.clientes[i][2] +'</option>';
    }
    $("select#id_Cliente").html(options);
  });

  $('#id_Cliente').on('change', function() {
      $.ajax({
          url: '/admin/getFacturas/'+$("select#id_Cliente").val(),
          data: '',
      }).done(function( data ) {
        var options;
        for (var i = 0; i < data.facturas.length; i++) {
          var date = data.facturas[i][2].split('-');
          options += '<option value="' + data.facturas[i][0] + '">' + data.facturas[i][1] + ' - ' + date[2] + "/" + date[1] + "/" + date[0] + '- Factura ' + data.facturas[i][3]+ '</option>';
        }
        $("select#id_Venta").html(options);
      });
    });

   $("#id_Cliente").select2();
   $("#id_Venta").select2();





</script>
{% endblock js %}

venta/templates/archivos_contador.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_admin/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
 {% block title %}Archivos Contador | Administración MundoVW{% endblock %}
{% block content %}
               
 
<form class="container" id="changelist-form"  method="post" action={% url 'descargar_archivo_contador_ventas' %}>
   {% csrf_token %}
  <fielset class="module aligned scheduler-border ">
    <legend class="scheduler-border  ">Archivos Contador </legend>
    <div class=" col-lg-6  " >
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class=" list-group-item active iva b "> <span class="glyphicon glyphicon-export"></span>
      <span class="text">exportar</span></button>
    </div>
  </fielset>    
</form>

{% endblock %}

<script type="text/javascript" src="/admin/jsi18n/"></script>
{% block bootstrap_admin_js %}
  <script src="{% static 'bootstrap_admin/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap_admin/js/base.js' %}"></script>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

<!-- <script src="{% static 'maglei/js/form_ventas.js' %}"></script> -->
{% endblock bootstrap_admin_js %}

venta/templates/ivaventas.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_admin/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
 {% block title %}Iva Ventas | Administración MundoW{% endblock %}
{% block content %}
</br>
</br>
<form id="changelist-form"  method="post" action={% url 'exportar_facturas' %}>
                                {% csrf_token %}
                                <fielset class="module aligned ">
                                  <div class=" col-lg-6">
                                {% for field in form %}
                                                            {{ field.errors }}
                                                                {%if "desde" in field.label_tag or "hasta" in field.label_tag  %}
                                                                  <div class="  col-lg-6 col-md-12 col-sm-12 pull-left">
                                                                {%else%}
                                                                  <div class="  col-lg-12 col-md-12 col-sm-12 pull-left">
                                                                {% endif%}
                                                                  <div class="col-lg-6 margen-top tlabel">{{ field.label_tag }}</div>
                                                                      {{ field }}
                                                                  </div>  
                                                        {%endfor%}
                                </br>
                                      </br></br></br></br></br>
                                  <div><h1> ------------------------<br></h1>
                                  </div>
                                <button type="submit" class="  list-group-item active iva"> <span class="glyphicon glyphicon-file"></span>
                                
                                <span class="text"   target="_blank" >Exportar a Excel</span></button>
                                </div>

                                
                                </fielset>    
</form>
 
{% endblock %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
{% block bootstrap_admin_js %}
  <script src="{% static 'bootstrap_admin/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap_admin/js/base.js' %}"></script>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script>
 $.datepicker.regional['es'] = {
 closeText: 'Cerrar',
 prevText: '<Ant',
 nextText: 'Sig>',
 currentText: 'Hoy',
 monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
 monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
 dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
 dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
 dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
 weekHeader: 'Sm',
 dateFormat: 'dd/mm/yy',
 firstDay: 1,
 isRTL: false,
 showMonthAfterYear: false,
 yearSuffix: ''
 };
 $.datepicker.setDefaults($.datepicker.regional['es']);
  $(function () {
    $("#fechaI").datepicker({
        onSelect: function(dateText, inst) {
          var fechaF = $('#fechaF').val();
          if (fechaF != '') {
            $.ajax({
              url: '/admin/ventas_json/' + fechaF +'/'+ dateText + '/',
              data: '',
            }).done(function( data ) {
              $('#id_total').val(data.total);
              $('#id_iva').val(data.iva);
              $('#id_neto_gravado').val(data.neto);
            });
          }
        }
      });
    $("#fechaF").datepicker({
        onSelect: function(dateText, inst) {
           var fechaI = $('#fechaI').val();
          if (fechaI != '') {
             $.ajax({
              url: '/admin/ventas_json/' + dateText +'/'+ fechaI + '/',
              data: '',
            }).done(function( data ) {
              $('#id_total').val(data.total);
              $('#id_iva').val(data.iva);
              $('#id_netoGravado').val(data.neto);
              
            });
          }
        }
      });
  });

</script>
<!-- <script src="{% static 'maglei/js/form_ventas.js' %}"></script> -->
{% endblock bootstrap_admin_js %}

venta/templates/pagina_error.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_admin/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />
 {% block title %}Error Afip | Administración MundoW{% endblock %}
{% block content %}
</br>
</br>
   <p id="foto" class="foto" ><img src="{% static 'img/AFIP-LOGO-638X200.jpg' %}"></p>
   Error
   {{cod}}
{% endblock %}
<script type="text/javascript" src="/admin/jsi18n/"></script>
{% block bootstrap_admin_js %}
  <script src="{% static 'bootstrap_admin/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap_admin/js/base.js' %}"></script>

  <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

{% endblock bootstrap_admin_js %}