articulo/urls.py
from django.conf.urls import url
from articulo import views

urlpatterns = [
            url(r"^all_articulos/$", views.all_articulos, name='all_articulos'),
            url(r'^articulo_json/(?P<oid>[0-9]+)/$', views.articulo_json, name='articulo_json'),
            url(r'^proveedor_articulo_json/(?P<oid>[\w\-]+)/$', views.proveedor_articulo_json, name='proveedor_articulo_json'),
            url(r"^crear_etiquetas/(\d+)$", views.crear_etiquetas, name='crear_etiquetas'),
            url(r"^cargar_articulos/$", views.cargar_articulos, name='cargar_articulos'),
    ]

proyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^select2/', include('select2.urls')),
    url(r'^$', RedirectView.as_view(url='/admin', permanent=True), name='home'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^admin/', include('articulo.urls')),
    url(r'^admin/', include('cheque.urls')),
    url(r'^admin/', include('cliente.urls')),
    url(r'^admin/', include('configuracion.urls')),
    url(r'^admin/', include('venta.urls')),
    url(r'^admin/', include('movimientos.urls')),
    #url(r'^admin/', include('ivaAfip.urls')),
]

venta/urls.py
from django.conf.urls import include, url
from venta import views
from cliente.views import cliente_json

urlpatterns = [url(r"^generarRemito/(\d+)$", views.generar_remito, name='generarRemito'),
               url(r"^generarFactura/(\d+)$", views.generar_factura, name='generarFactura'),
               url(r"^generarPresupuesto/(\d+)$", views.generar_presupuesto, name='generarPresupuesto'),
               url(r"^generarNotaCredito/(\d+)$", views.generarNotaCredito, name='generarNotaCredito'),
              # url(r"^crearVenta/(\d+)$", views.crearVenta, name='crearVenta'),
               url(r"^generarCompra/(\d+)$", views.generar_compra, name='generarCompra'),
               url(r"^pagina_error/(?P<codigo>.+)$", views.pagina_error, name='pagina_error'),
               url(r"^notaCredito/$", views.notaCredito, name='notaCredito'),
               url(r"^ivaventas/$", views.ivaventas, name='ivaventas'),
               url(r"^exportar_facturas/$", views.exportar_facturas, name='exportar_facturas'),
               url(r"^getFacturas/(\d+)$", views.getFacturas, name='getFacturas'),
               url(r'^remito_json/(?P<oid>[0-9]+)/$', views.remito_json, name='remito_json'),
               url(r'^ventas_json/(?P<Iday>\d{1,2})/(?P<Imonth>\d{1,2})/(?P<Iyear>\d{4})/(?P<Fday>\d{1,2})/(?P<Fmonth>\d{1,2})/(?P<Fyear>\d{4})/$', views.ventas_json, name='ventas_json'),
               url(r'^tarjeta_json/(?P<oid>[0-9]+)/$', views.tarjeta_json, name='tarjeta_json'),
               url(r"^caja_diaria_json/(?P<parametro>.+)$", views.caja_diaria_json, name='caja_diaria_json'),
               url(r"^recargo_tarjeta/(?P<nombre>.+)/(?P<cuotas>\d{1,2})/$", views.recargo_tarjeta, name='recargo_tarjeta'),
               url(r"^generar_archivos_contador/$", views.contador_ventas, name='contador_ventas'),
               url(r"^descargar_archivo_contador_ventas", views.descargar_archivo_contador_ventas, name="descargar_archivo_contador_ventas"),
               #url(r'^cliente_json/(?P<oid>[0-9]+)/$', cliente_json, name='cliente_json'),
]

articulo/models.py
# -*- coding: utf-8 -*-
from decimal import Decimal

import datetime

import select2.fields
import select2.models
from django.db import models

from configuracion.views import CONFIRMACION

# articulos
from django.db.models import Max, Q

from cliente.models import Proveedor


class TipoIva:
    UNO = '21.00'
    DIEZ = '10.50'

TIPO_IVA = (
    (TipoIva.UNO, '21.00'),
    (TipoIva.DIEZ, '10.50'),
    )

def numero_formateado():
    no = Articulo.objects.aggregate(siguiente_numero=Max('id'))
    if no is None:
        return u"ART-{:08d}".format(1)
    if no['siguiente_numero'] is None:
        return u"ART-{:08d}".format(1)
    return u"ART-{:08d}".format(no['siguiente_numero'] + 1)


class ArticuloRubro(models.Model):
    nombre = models.CharField(u'Nombre', max_length=150)

    class Meta:
        verbose_name = u'Rubro'
        verbose_name_plural = u'Rubros'

    def __unicode__(self):
        return u'{0}'.format(self.nombre)


class ArticuloSubRubro(models.Model):
    nombre = models.CharField(u'Nombre', max_length=150)
    rubro = models.ForeignKey(ArticuloRubro, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = u'Sub rubro'
        verbose_name_plural = u'Sub rubros'

    def __unicode__(self):
        return u'{0}'.format(self.nombre)


class Articulo(models.Model):
    numero = models.CharField(u'numero de articulo', max_length=60, default=numero_formateado)
    codigo = models.CharField(u'Codigo', max_length=50, blank=True, null=True)
    descripcion = models.CharField(u'Descripción', max_length=150, null=False)
    rubro = select2.fields.ForeignKey(ArticuloSubRubro, on_delete=models.SET_NULL, blank=True, null=True)
    codigo_proveedor = models.CharField(u'Codigo Proveedor', max_length=50, blank=True, null=True)
    proveedor = select2.fields.ForeignKey(Proveedor,
                                          ajax=True,
                                          search_field='apellido',
                                          related_name=u'proveedor',
                                          overlay="...",
                                          js_options={
                                              'quiet_millis': 200,
                                          })
    costo = models.DecimalField(u'Costo', max_digits=10, decimal_places=2, default=0.00)
    iva = models.CharField(u'IVA (%)', choices=TIPO_IVA, default=TipoIva.UNO, max_length=5)
    costo_iva = models.DecimalField(u'Costo + IVA', max_digits=20, decimal_places=2, default=0.00)
    ganancia = models.DecimalField(u'Ganancia', max_digits=20, decimal_places=2, default=0.00)
    precio_venta = models.DecimalField(u'Precio de venta', max_digits=20, decimal_places=2, default=0.00)
    stock = models.IntegerField(u'Stock', default=0)
    stock_deposito = models.IntegerField(u'Stock Deposito', default=0)

    class Meta:
        verbose_name_plural = u'Articulos'

    def __unicode__(self):
        return u'{0} '.format(self.codigo)

    def save(self, *args, **kwargs):
        costo = self.costo
        self.costo_iva = Decimal(costo) + (Decimal(costo) * Decimal(self.iva)) / Decimal(100)
        self.precio_venta = (self.costo_iva) + (Decimal(self.costo_iva) * Decimal(self.ganancia) / Decimal(100))
        super(Articulo, self).save(*args, **kwargs)

class Impresion(models.Model):
    fecha = models.DateField(u'Fecha', default=datetime.date.today)
    carga_stock = models.CharField(u'Carga Stock', max_length=2, choices=CONFIRMACION, default='NO')

    class Meta:
        verbose_name = u'Impresion de Etiquetas'
        verbose_name_plural = u'Impresion de Etiquetas'

# --Articulo
class ImpresionArticulo(models.Model):
    impresion = models.ForeignKey(Impresion, on_delete=models.CASCADE)
    articulo = select2.fields.ForeignKey(Articulo,
                                         ajax=True,
                                         search_field=lambda q: Q(codigo__icontains=q),
                                         related_name=u'ArticulosImpresion',
                                         overlay="...",
                                         js_options={
                                             'quiet_millis': 200,
                                         },
                                         on_delete=models.PROTECT)
    cantidad = models.IntegerField(u'Cantidad', default=0)

    def __unicode__(self):
        return u''

articulo/forms.py
# -*- coding: utf-8 -*-
# vim:expandtab ts=4 sw=4
from django import forms


class formActualizarArticulos(forms.Form):
    costo = forms.DecimalField(label=u'Costo %', required=False, max_digits=20, decimal_places=2,
                               widget=forms.NumberInput(attrs={'class': "form-control vTextField"}))
    iva = forms.DecimalField(label=u'Iva %', required=False, max_digits=20, decimal_places=2,
                             widget=forms.NumberInput(attrs={'class': "form-control vTextField"}))
    ganancia = forms.DecimalField(label=u'Ganancia %', required=False, max_digits=20, decimal_places=2,
                                  widget=forms.NumberInput(attrs={'class': "form-control vTextField"}))


class formActualizarPrecios(forms.Form):
    Proveedor = forms.IntegerField(widget=forms.Select(attrs={'class': "form-control"}))
    archivo = forms.FileField()

articulo/views.py
import csv
from decimal import Decimal

import xlrd as xlrd
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from articulo.forms import formActualizarPrecios
from articulo.models import Articulo
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from easy_pdf.rendering import render_to_pdf_response
from django.template.defaultfilters import *
from articulo.models import ImpresionArticulo
# operacion= True es suma de articulos en stock
from cliente.models import Proveedor
from django.db.models import Q


def stock_articulos(articulos,operacion):
    if operacion:
        for a in articulos:
            articulo = Articulo.objects.get(id=a.articulo.id)
            articulo.stock += a.cantidad
            articulo.save()
    else:
        for a in articulos:
            articulo = Articulo.objects.get(id=a.articulo.id)
            articulo.stock -= a.cantidad
            articulo.save()


# JSONs
@login_required
def proveedor_articulo_json(request, oid):
    if Articulo.objects.filter(codigo_proveedor=oid).exists():
        obj = Articulo.objects.get(codigo_proveedor=oid)
        des = obj.descripcion
        numero = obj.id
    else:
        des = 'El articulo no existe'
        numero = 0
    data = {
        'id': numero,
        'descripcion': des,
    }
    return JsonResponse(data)

@login_required
def all_articulos(request):
    response = JsonResponse(dict(items=list(Articulo.objects.all().values_list('id', 'codigo'))))
    return HttpResponse(response, content_type='application/json')

@login_required
def articulo_json(request, oid):
    obj = Articulo.objects.get(id=oid)
    data = {
        'id': obj.id,
        'precio': obj.precio_venta,
        'iva': obj.iva,
        'nombre': obj.descripcion,
        'descripcion': obj.descripcion,
    }
    return JsonResponse(data)

@register.filter(name='contador')
def contador(cantidad):
    return range(cantidad)

@login_required
def crear_etiquetas(request,id):
    impresiones = ImpresionArticulo.objects.filter(impresion=id)
    lista = []
    sublista = []
    pos = 0
    ancho = 4
    for art in impresiones:
        cant = 0
        while cant < art.cantidad:
            if pos < ancho:
                sublista.append(art.articulo)
                pos += 1
            else:
                lista.append(sublista)
                sublista = []
                sublista.append(art.articulo)
                pos = 1
            cant += 1
    lista.append(sublista)
    sublista = []
    print lista
    title = 'etiquetas'
    pagesize = "A4"
    template_name = "etiquetaPDF.html"
    return render_to_pdf_response(request, template_name, locals())

@login_required
def cargar_articulos(request):
    print ('entro a Cargar Articulos')
    template = "ActualizarPrecios.html"
    form = formActualizarPrecios()
    cant = 0
    row_error = list()
    if request.method == "POST":
        form = formActualizarPrecios(request.POST, request.FILES)
        if form.is_valid():
            id_proveedor = form.cleaned_data['Proveedor']
            prov = Proveedor.objects.get(id=id_proveedor)
            data = request.FILES.get('archivo')

            try:
                book = xlrd.open_workbook(data.name, file_contents=data.read())  # Open book
                xl_sheet = book.sheets()[0]  # Get sheet in index 0
                num_cols = xl_sheet.ncols  # Number of columns
                for row in range(0, xl_sheet.nrows):  # Iterate through rows
                    # print 'Row: %s' % row_idx  # Print row number
                    # for col_idx in range(0, num_cols):  # Iterate through columns
                    codigo = str(xl_sheet.cell(row, 0).value) + '-' + prov.proveedor_cod

                    articulo, created = Articulo.objects.get_or_create(
                        proveedor=prov,
                        codigo_proveedor=xl_sheet.cell(row, 0).value,
                    )

                    if created:
                        articulo.descripcion = xl_sheet.cell(row, 1).value

                    articulo.costo = float(xl_sheet.cell(row, 2).value)
                    articulo.precio_venta = float(xl_sheet.cell(row, 3).value)
                    articulo.codigo = str(xl_sheet.cell(row, 0).value) + '-' + prov.proveedor_cod
                    articulo.save()
                return HttpResponseRedirect("../articulo/articulo")
            except:
                context = {
                    'form': form,
                    'error': 'Archivo no compatible. El archivo debe ser de tipo Excel'
                }
                return render(request, template, context)

    context = {
        'form': form
    }
    return render(request, template, context)

articulo/templates/ActualizarPrecios.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls admin_static admin_modify %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap_admin/css/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}" />
<link rel="stylesheet" type="text/css" href="{% static "admin/css/changelists.css" %}" />

{% block title %}Actualizar Precios | Administración Iturralde{% endblock %}
{% block content %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />               
 
   

<form class="centrado" id="changelist-form" form enctype="multipart/form-data" method="post" action={% url 'cargar_articulos' %}>
   {% csrf_token %}
  <fielset class="module aligned scheduler-border ">
    <legend class="scheduler-border  ">Cargar/Actualizar Artículos</legend>

      {% if error %}
        <div class="alert alert-danger" role="alert">
            <strong>Error!</strong> {{ error }}
        </div>
      {% endif %}

      <div class=" col-lg-3  " >
      {% for field in form %}
            {{ field.errors }}

                  <div class="form-group">
                      <label>{{ field.label_tag }}</label>
                      {{ field }}
                  </div>
      {%endfor%}

      <button type="submit" class="btn btn-primary">
            <span class="glyphicon glyphicon-export"></span>
            <span class="text">Cargar</span>
      </button>
    </div>
  </fielset>    
</form>

{% endblock %}

<script type="text/javascript" src="/admin/jsi18n/"></script>
{% block bootstrap_admin_js %}
  <script src="{% static 'bootstrap_admin/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'bootstrap_admin/js/base.js' %}"></script>

 <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
{% endblock bootstrap_admin_js %}
{% block js %}
  <script>
    $.ajax({
        url: '/admin/all_proveedores/',
        data: '',
    }).done(function( data ) {
      var options;
      options += '<option selected disabled > Seleccione un Proveedor </option>';
      for (var i = 0; i < data.proveedores.length; i++) {
        options += '<option value="' + data.proveedores[i][0] + '">' + data.proveedores[i][1] + '</option>';
      }
      $("select#id_Proveedor").html(options);
    });

    $("#id_Proveedor").select2();
  </script>
{% endblock js %}

articulo/templates/ListadoArticulosPDF.html
{% extends "easy_pdf/base.html" %}

{% block layout_style %}

    <style type="text/css">
       
        @page {
         size: {{ pagesize|default:"A4" }};

     
       @frame header_frame {
            -pdf-frame-content: header_content_right;
            left:450pt; width: 300pt; top: 70pt; height: 80pt;
        }
       @frame header_frame {
            -pdf-frame-content: foto;
            left:40pt;  top: 15pt;
        }
        @frame header_frame {           /* Static Frame */
            -pdf-frame-content: datos_empresa;
            left: 430pt; width: 200pt; top: 18pt; height: 50pt;
        }
        @frame header_frame {
            -pdf-frame-content: header_content_fecha;
            left: 270pt; width:100pt; top: 70pt; height: 80pt;
        }
        @frame header_frame {
            -pdf-frame-content: header_content_fecha_cliente;
            left: 270pt; width:500pt; top: 55pt; height: 50pt;
        }
        @frame header_frame {
            -pdf-frame-content: header_content_table;
            left: 40pt;width:560pt; top: 100pt; height: 730pt;
        }

        @frame content_frame {
            left: 40pt;width:560pt; top: 100pt; height: 730pt;
        }

       @frame header_frame {
            -pdf-frame-content: Titulo;
            left: 260pt; width: 350pt; top: 30pt; height: 160pt;
        }

        @frame header_frame {           /* Static Frame */
            -pdf-frame-content: footer_content_total_right;
            left: 240pt;width:120pt; top: 525pt;
        }
        @frame header_frame {
            -pdf-frame-content: encuadre;
            left: 40pt;width:520pt; top: 15pt;
        }

    }

    </style>
{% endblock %}

{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Lato", "Helvetica", "sans-serif";
            color: #333333;
        }

        h4 {
            line-height: 10% ;

        }
        .dd{
            max-width: 50px;
            max-height: 50px;
        }
         .datos{
            text-align: right;
        }

        .centrado{
           padding-left: 50px;
        }

        h5 { font-size: 12px;}
        .numero{
           margin-right: 25px;
           text-align:right;
        }
        .hr {
            display: block;
            height: 1px;
            border: 0;
            border-top: 2px solid #000;
            border-bottom: 2px solid #000;
            margin: 1em 0;
            padding: 3px;

        }
        tr{
            padding-top: 3px;
            padding-bottom: 0px;
            margin-bottom: 0px;
            border-bottom: 0.5px solid #000;
            border-top: 0.5px solid #000;
        }
        .no_linea{
            border-top: none;
            border-bottom: none;
            padding-left: 10px;
        }
        .encuadre{
             border: 0.5px solid #000;
        }
        .pal{
            padding-bottom: 1040px;

        }
        .venta{
            padding-left: 3px;
        }
        .tabla_letra{
         font-size: 14px;
        }
         .titulo{
         font-size: 16px;
        }
        .total{
            text-align:right;
        }
        .foto{
            padding-left: 0px;
            zoom : 80%;
        }

    </style>
{% endblock %}
{%block page_header%}
     <div id="encuadre" class ="encuadre">
        <h6 class="pal">
            </br>
            </br>
            </br>
        </h6>
    </div>
    <p id="foto" class="foto" ><img src="{{conf.url_estaticos}}/resumenCuenta.jpg"></p>
    
    <div id="Titulo" class="titulo" >
          <h1 >
                Listado de Articulos
          </h1>
        
    </div>
    <div id="supPresupuesto" class ="prepSup"> <h6> &nbsp; </h6></div>
        <div id="header_content_fecha" >
            <h1>
                    Fecha: {{fecha.day}}/{{fecha.month}}/{{fecha.year}}
            </h1>
        </div>
    <div id="header_content_right" >
         <h1>  Página: <pdf:pagenumber /> de <pdf:pagecount/> </h1>
    </div>
    <table class="tabla_letra">
        <thead>
            <tr>
                <th width="400">Detalle </th>
                <th width="120">Precio </th>
            </tr>
        </thead>
    </table>
{% endblock %}

{% block content %}
     <table>
        <tbody>
                {% for a in articulos %}

                        <tr >
                            <td width="400" class="venta">
                                 {{a.codigo}} - {{a.descripcion}}
                            </td>
                            <td width="120" class="numero">
                                $ {{a.precio_venta}}
                            </td>
                        </tr>

               {%endfor%}
    </table>
{% endblock %}



       
           

articulo/templates/etiquetaPDF.html
{% extends "easy_pdf/base.html" %}

{% block layout_style %}
    <style type="text/css">
        @page {
         size: {{ pagesize}};


       /* 40 LETRAS DESCRIPCION */
        @frame content_frame {           /* content_frame */
             left: 15pt; width:570pt; top: 20pt;
        }

    }

    </style>
{% endblock %}


{% block extra_style %}
    <style type="text/css">
        body {
            font-family: "Lato", "Helvetica", "sans-serif";
            color: #333333;
        }
    td {
        padding-top: 20px; 
    }
    .precio {
        text-align: center;
        font-size: 70pt;
        margin-top: inherit;
    }

    </style>
{% endblock %}
{%block page_header%}



{% endblock %}
{% block content %}
    <div>
        <table>
            {% for sublist in lista %}
                <tr>
                {% for cod in sublist %}
                    <td>
                        <pdf:barcode barheight="200" barwidth="6" value={{cod.codigo}}  type="code128" humanreadable="1" fontsize= "100px" align="baseline" /> <br>
                        <h3 class="precio"> $ {{ cod.precio_venta }}</h3>
                    </td>
                {%endfor%}
                </tr>
            {%endfor%}
        </table>
    </div>
{% endblock %}
{%block page_foot%}



{% endblock %}